<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6</TargetFrameworks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <PropertyGroup>
    <PackageLicenseFile>LICENSE.MD</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="LICENSE.MD" Pack="true" PackagePath="LICENSE.MD">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>MyKey.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>Slidoteka.TrackerEnabledDbContext.Common</PackageId>
    <Authors>Bilal Fazlani, Yury Kozhanovskiy</Authors>
    <Company>Bilal</Company>
    <Product>Common Library for TrackerEnabledDbContext</Product>
    <VersionSuffix>$(VersionSuffix)</VersionSuffix>
    <Version>4.0</Version>
    <Version Condition=" '$(VersionSuffix)' != '' ">$(Version)-$(VersionSuffix)</Version>
    <AssemblyVersion>4.0</AssemblyVersion>
    <FileVersion>4.0</FileVersion>
    <PackageTags>SQL Entity Framework Tacking Audit C# Database ASP.NET</PackageTags>
    <Copyright>2020</Copyright>
    <RequireLicenseAcceptance>false</RequireLicenseAcceptance>
    <ProjectUrl>https://github.com/mcgrab/tracker-enabled-dbcontext</ProjectUrl>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Description>Common nuget package required for TrackerEnabledDbContext &amp; TrackerEnabledDbContext.Identity</Description>
    <Summary>Common nuget package required for TrackerEnabledDbContext &amp; TrackerEnabledDbContext.Identity</Summary>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.20" />
  </ItemGroup>

</Project>
