<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6</TargetFrameworks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>MyKey.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <PackageLicenseFile>LICENSE.MD</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="LICENSE.MD" Pack="true" PackagePath="LICENSE.MD">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <PropertyGroup>
    <PackageId>Slidoteka.TrackerEnabledDbContext</PackageId>
    <Authors>Bilal Fazlani, Yury Kozhanovskiy</Authors>
    <Company>Bilal Fazlani</Company>
    <Product>Tracker Enabled DbContext</Product>
    <VersionSuffix>$(VersionSuffix)</VersionSuffix>
    <Version>4.0</Version>
    <Version Condition=" '$(VersionSuffix)' != '' ">$(Version)-$(VersionSuffix)</Version>
    <AssemblyVersion>4.0</AssemblyVersion>
    <FileVersion>4.0</FileVersion>
    <PackageTags>SQL Entity Framework Tracking Audit C# Database ASP.NET</PackageTags>
    <Copyright>2020</Copyright>
    <RequireLicenseAcceptance>false</RequireLicenseAcceptance>
    <ProjectUrl>https://github.com/bilal-fazlani/tracker-enabled-dbcontext</ProjectUrl>
    <RepositoryUrl>https://github.com/mcgrab/tracker-enabled-dbcontext</RepositoryUrl>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Description>
      Use this to extend Entity Framework functionality to store changes in database. This is very useful for auditing purpose. It stores WHO changed WHAT and WHEN. It will let you choose which tables and columns you want to track with the help of attributes.

      NOTE: TO USE WITH ASP.NET MVC 5 IDENTITY, USE : TrackerEnabledDbContext.Identity

      Click here to get started : http://bilal-fazlani.blogspot.in/2013/09/adding-log-audit-feature-to-entity.html
    </Description>
    <Summary>
      Use this to extend Entity Framework functionality to store changes in database. This is very useful for auditing purpose. It stores WHO changed WHAT and WHEN. It will let you choose which tables and columns you want to track with the help of attributes.

      NOTE: TO USE WITH ASP.NET MVC 5 IDENTITY, USE : TrackerEnabledDbContext.Identity

      Click here to get started : http://bilal-fazlani.blogspot.in/2013/09/adding-log-audit-feature-to-entity.html
    </Summary>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.20" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TrackerEnabledDbContext.Common\TrackerEnabledDbContext.Common.csproj" />
  </ItemGroup>
  

</Project>
